name: Makefile CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install necessary packages
      run: sudo apt-get update && sudo apt-get -y install pandoc texlive-latex-recommended texlive-fonts-recommended texlive-xetex
           
    - uses: actions/checkout@v4

    - name: Make the pdf
      run: make

    - name: Upload the PDF
      uses: actions/upload-artifact@v4
      with:
        name: The ebook
        path: software-testing-laboon-ebook.pdf
